### ISSUE TITLE
Changing the background image

### ISSUE THREAD

**Issue by steveothesane** [JOHLC/transparentblue#14]
@JOHLC this is an amazing theme but I would like to change the background image to something that is a bit darker such as a space themed image. There aren't any instructions for how to do so.  Looking at the YAML code it would appear that the image is embedded in the file as a Base64 encoded image but I'm not sure how to change that.  Any help you can give would be appreciated.  Thank you.

**Comment by JOHLC** [comment]
#15 added documentation explaining the process
You can find the documentation [here](https://github.com/JOHLC/transparentblue#changing-the-background-image)

**Comment by steveothesane** [comment]
Sweet!  Thank you.

**Comment by JOHLC** [comment]
Welcome! Thanks for the interest
