### ISSUE TITLE
Different background image per view

### ISSUE THREAD

**Issue by thisisbenwoo** [JOHLC/transparentblue#26]
@JOHLC 
Thanks for this great theme. I'm wondering if it is possible to have a different background image per view please?
Thank you.

**Comment by JOHLC** [comment]
As this isn't an issue specific to this theme, I'll be closing this issue. 
That said, a very quick Google search makes me think this is possible

"Background image per tab in lovelace view? - Configuration / Frontend - Home Assistant Community" https://community.home-assistant.io/t/background-image-per-tab-in-lovelace-view/283471

"Different backgrounds for each views - Configuration - Home Assistant Community" https://community.home-assistant.io/t/different-backgrounds-for-each-views/142368

It would be totally independent of a custom theme like this and need to be unique to your Lovelace.

**Comment by thisisbenwoo** [comment]
Thanks for the prompt response Joel. I actually tried both the suggestions in the links you provided prior to posing this question, but it didn't work with your theme. Thank you all the same. Your theme is great!

**Comment by JOHLC** [comment]
Thanks! 

I've never tried but maybe removing the background from the theme file will allow you to.
