### ISSUE TITLE
Transparent Blue Uninstall problem

### ISSUE THREAD

**Issue by berkavil** [JOHLC/transparentblue#29]
The TransparentBlue theme can't be uninstalled.

**To Reproduce**
after click: HACS/Remove integration - the msg "Can't be uninstalled" apears

LOG: 
2022-02-17 23:35:52 ERROR (MainThread) [custom_components.hacs] <Theme JOHLC/transparentblue> Path /config/themes/ is blocked from removal
2022-02-17 23:35:52 ERROR (MainThread) [custom_components.hacs] Could not uninstall

**Expected behavior**
should be removed from file folder automatically and also should disapear from hacs list of installed themes...

**Screenshots**
![image](https://user-images.githubusercontent.com/84925164/154583545-bbbc0ebd-3c26-4333-bf05-e3bfd00af584.png)

HA version 2022.2.6
PC-Chrome

I deleted all files manually, but the entry from the list of HACS installed themes can't be deleted... (or I don't know how).

**Comment by JOHLC** [comment]
Weird. 

1. 
![image](https://user-images.githubusercontent.com/63735432/161842268-b49591af-619a-48f7-8618-0995c4c22aa7.png)
2. 
![image](https://user-images.githubusercontent.com/63735432/161842290-1d7c05cf-af74-476e-95fd-f88e35f1e1fe.png)


And it was removed without issues.  Do you maybe have it added as a custom repo still? 
Maybe there was a bug with your version of HA? Can you try again with the latest update?

**Comment by berkavil** [comment]
Hallo, it may be the custom repo – but installed via HACS, and the „remove“ button just doesnt work (I deleted the files manually from the folder but can’t get rid of the entry under HACS/interface

 

Vilem

**Comment by JOHLC** [comment]
Could you try removing it from the custom repo list in HACS? 
![image](https://user-images.githubusercontent.com/63735432/162029630-4b304c2c-148a-40e7-99c3-e92be5db7511.png)

Then see if HACS allows you to remove it?   

Also are you running the latest everything as of today? 
Another thought: Maybe try re-installing and then uninstalling again?

**Comment by berkavil** [comment]
Thanks for the clue - the todays update solved it! it is ok now.

thank you indeed.

Vilem

**Comment by JOHLC** [comment]
Glad we got it resolved!
