### ISSUE TITLE
Different color

### ISSUE THREAD

**Issue by Shredder5262** [JOHLC/transparentblue#36]
Not an issue at all per se. I want to know how i can change the color? I like the transparent tiles as they they are and the styling...just want to know how i can do different tints of color. What if i want a transparent green accent, or yellow? I like this theme very much...instructions on how to use a base 64 image was a real game changer for me, I just want to be able to use different accent colors to compliment the background image.

**Comment by JOHLC** [comment]
@Shredder5262 -- I spent a lot of time getting all the colors to mesh well with each other, so there isn't just one single color value that you can update. 

Some (not all) of the color variables are listed under the "Color variables" section here: https://github.com/JOHLC/transparentblue/blob/40f30f25f62d37c7a5f500e813683255ff7ec654/themes/transparentblue.yaml#L7 

You can try playing around with those. 

Here is the Home Assistant documentation on how it works:
[Theme-format](https://www.home-assistant.io/integrations/frontend/#theme-format)


Thanks for liking my theme!
